CREATE TABLE resources (
    id text PRIMARY KEY,
    provider text NOT NULL,
    account_id text NOT NULL,
    region text NOT NULL,
    provider_resource_id text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    UNIQUE (provider, account_id, region, provider_resource_id)
);

CREATE TABLE recommendations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    plugin_id text NOT NULL,
    algorithm_id text NOT NULL,
    status text NOT NULL,
    expires_at timestamptz,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE actions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recommendation_id bigint NOT NULL REFERENCES recommendations(id) ON DELETE RESTRICT,
    resource_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    idempotency_key text NOT NULL UNIQUE,
    status text NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE action_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id bigint REFERENCES actions(id) ON DELETE RESTRICT,
    recommendation_id bigint REFERENCES recommendations(id) ON DELETE RESTRICT,
    resource_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL,
    CHECK (action_id IS NOT NULL OR recommendation_id IS NOT NULL)
);

CREATE TABLE jobs (
    id bigint PRIMARY KEY,
    action_id bigint NOT NULL UNIQUE REFERENCES actions(id) ON DELETE RESTRICT,
    recommendation_id bigint NOT NULL REFERENCES recommendations(id) ON DELETE RESTRICT,
    resource_id text NOT NULL REFERENCES resources(id) ON DELETE RESTRICT,
    state text NOT NULL,
    next_run timestamptz NOT NULL,
    payload jsonb NOT NULL,
    updated_at timestamptz NOT NULL
);
